[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["npm ci --prefer-offline --no-audit"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "./start.sh"

[variables]
NIXPACKS_TURBO_APP_NAME = "trainer-dashboard"
NODE_ENV = "production"