[build]
builder = "nixpacks"
buildCommand = "npm install && turbo run build --filter=trainer-dashboard"

[deploy]
startCommand = "./start.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
# Health check mit kürzerem Timeout
healthcheckPath = "/api/health"
healthcheckTimeout = 30

[[services]]
name = "nv-coaching-trainer-dashboard"
type = "web"

[services.nv-coaching-trainer-dashboard]
port = 3000