[build]
builder = "nixpacks"
buildCommand = "npm install && turbo run build --filter=trainer-dashboard"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "nv-coaching-trainer-dashboard"
type = "web"

[services.nv-coaching-trainer-dashboard]
port = 3000